name: Generate File and Create Pull Request

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '**'

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Gradle Set up
        uses: gradle/actions/setup-gradle@v4

      - name: Create a new branch for the PR
        run: |
          BRANCH_NAME="${{ github.head_ref }}-added-files"
          git checkout -b $BRANCH_NAME

      - name: Run Gradle task from plugin
        run: ./gradlew build -parallel

      - name: Commit generated file
        run: |
          if [ -z "${{ github.event.pull_request.user.email }}" ]; then
            git config --global user.email "no-email@users.noreply.github.com"
          else
            git config --global user.email "${{ github.event.pull_request.user.email }}"
          fi
          
          git status
          
          git config --global user.name "${{ github.event.pull_request.user.login }}"
          git add -A
          git commit -m "Add files"

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git remote set-url origin https://${GITHUB_TOKEN}@github.com/olegmak02/plugin_test.git
          git push --set-upstream origin "${{ github.head_ref }}-added-files"
