name: Generate File and Create Pull Request

on:
  pull_request:
    branches:
      - "main"
    types: [ closed ]

permissions:
  contents: write
  pull-requests: write

env:
  new-branch: ${{ github.head_ref }}-added-files

jobs:
  generate-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Gradle Set up
        uses: gradle/actions/setup-gradle@v4

      - name:
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${new-branch}

      - name: Checkout new branch
        uses: actions/checkout@v4
        with:
          ref: ${new-branch}

      - name: Main work
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: ./gradlew myTask -Pbranch=${new-branch}

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.TOKEN }}
          branch: ${{ github.head_ref }}
