name: Generate File and Create Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write
  actions: write

env:
  label: " code "

jobs:
  generate-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR labels
        id: pr-labels
        uses: irby/get-labels-on-push@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'push' }}

      - name: Skip early
        if: ${{ steps.pr-labels.outcome == 'skipped' || !contains(steps.pr-labels.outputs.labels, env.label) }}
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ secrets. GITHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Gradle Set up
        uses: gradle/actions/setup-gradle@v4

      - name: Generate branch name
        id: generate-branch
        if: ${{ !cancelled() }}
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message || 'added-generated-ids' }}"
          NEW_BRANCH="autogenerated/$(echo $COMMIT_MESSAGE | tr ' ' '-')"
          echo "new_branch=$NEW_BRANCH" >> $GITHUB_ENV

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        if: ${{ !cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.new_branch }}

      - name: Checkout new branch
        uses: actions/checkout@v4
        if: ${{ !cancelled() }}
        with:
          ref: ${{ env.new_branch }}

      - name: Main work
        if: ${{ !cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          ./gradlew bootRun

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        if: ${{ !cancelled() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.new_branch }}
          commit-message: "Automatically added changed files with generated ids"
          base: 'main'

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        if: ${{ !cancelled() }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          repo: olegmak02/plugin_test

