name: Generate File and Create Pull Request

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write
  actions: write

env:
  label: " code "

jobs:
  generate-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Get PR labels
        id: pr-labels
        uses: irby/get-labels-on-push@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout new branch
        id: checkout-branch
        uses: actions/checkout@v4
        if: ${{ !cancelled() && contains(steps.pr-labels.outputs.labels, env.label) }}
        with:
          ref: 'main'

      - name: Run Main Code
        if: ${{ steps.checkout-branch.outcome != 'skipped'  }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          ./gradlew bootRun
          git add -A
          git commit -m "Automatically added changed files with generated ids"
          git push
