name: Generate File and Create Pull Request

on:
  push:
    branches:
      - "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Gradle Set up
        uses: gradle/actions/setup-gradle@v4

      - name: Create PR
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: ./gradlew myTask
