name: Generate File and Create Pull Request

on:
  pull_request:
    - "**"

jobs:
  generate-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Run Gradle task from plugin
        run: ./gradlew helloTask

      - name: Create a new branch for the PR
        run: |
          BRANCH_NAME="generated-file-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $BRANCH_NAME

      - name: Commit generated file
        run: |
          git add -A
          git commit -m "Add files"
          git push --set-upstream origin $BRANCH_NAME

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: git push
