name: Generate File and Create Pull Request

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "**"

permissions:
  contents: write
  pull-requests: write

env:
  new_branch: ${{ github.head_ref }}-added-files

jobs:
  generate-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Gradle Set up
        uses: gradle/actions/setup-gradle@v4

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        if: |
          github.event.pull_request.merged == true &&
          contains(github.event.pull_request.labels.*.name, 'generate-id')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.new_branch }}

      - name: Checkout new branch
        uses: actions/checkout@v4
        if: success()
        with:
          ref: ${{ env.new_branch }}

      - name: Main work
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew generateIds
          ./gradlew commitPushTask -Pbranch=${{ env.new_branch }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        if: success()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.new_branch }}
          base: "main"
